# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=256, verbose_name='наименование')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/products', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('vendor_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='артикул')),
                ('title', models.CharField(max_length=256, verbose_name='наименование')),
                ('title_image', models.ImageField(upload_to='catalog/products', verbose_name='титульное изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='цена')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='вес, гр')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('ingredients', models.TextField(blank=True, null=True, verbose_name='состав')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'ordering': ['-created'],
                'verbose_name_plural': 'Товары',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='товар'),
        ),
    ]
